.template_repo: &repo
  project: &ci_tmpl 'tag-messenger/ci-templates'
  ref: &ci_tmpl_vers 'v1.4.0'

variables:
  CI_TMPL_PROJECT: *ci_tmpl
  CI_TMPL_PROJECT_VERSION: *ci_tmpl_vers


include:
  - { <<: *repo, file: /common.yml }
  - { <<: *repo, file: /plugin.yml }
